-- High-quality questions for all puzzles
-- These questions are mysterious, engaging, and don't reveal the location

UPDATE puzzle_translations pt
SET clue_1_text = CASE p.id
  -- Space & Technology
  WHEN 94 THEN 'Where and when did humanity launch its first successful crewed mission to land on the Moon?'
  WHEN 111 THEN 'Where and when was a revolutionary touchscreen device unveiled that would change mobile computing forever?'
  WHEN 118 THEN 'Where and when did a Harvard dorm room project launch that would connect billions of people worldwide?'
  WHEN 170 THEN 'Where and when did humanity launch the first artificial satellite into Earth''s orbit?'
  WHEN 200 THEN 'Where and when was a space telescope launched that would revolutionize our view of the universe?'
  
  -- Iconic Structures
  WHEN 95 THEN 'Where and when was a controversial iron lattice tower completed for a world''s fair, initially despised by critics?'
  WHEN 96 THEN 'Where and when did a colossal copper statue arrive as a gift from France, symbolizing freedom?'
  WHEN 98 THEN 'Where and when did the clock tower of the Palace of Westminster first chime?'
  WHEN 99 THEN 'Where and when was a white marble mausoleum completed as an emperor''s tribute to his beloved wife?'
  WHEN 100 THEN 'Where and when was a massive Art Deco statue of Christ erected atop a mountain?'
  WHEN 101 THEN 'Where and when did a distinctive sail-shaped performing arts center open its doors?'
  WHEN 102 THEN 'Where and when was an iconic suspension bridge painted in International Orange completed?'
  WHEN 107 THEN 'Where and when was a monumental sculpture of four presidents'' faces completed in granite?'
  WHEN 120 THEN 'Where and when did the world''s tallest building pierce the sky at 828 meters?'
  WHEN 122 THEN 'Where and when were giant white letters erected on a hillside to advertise a housing development?'
  WHEN 124 THEN 'Where and when was a freestanding bell tower completed that immediately began tilting due to soft ground?'
  WHEN 127 THEN 'Where and when was an ancient amphitheater completed that could hold 50,000 spectators for gladiatorial games?'
  WHEN 128 THEN 'Where and when were three massive limestone structures completed as eternal tombs for pharaohs?'
  WHEN 129 THEN 'Where and when was a prehistoric monument of massive standing stones arranged in a mysterious circle?'
  WHEN 130 THEN 'Where and when was the world''s largest religious monument completed, dedicated to Vishnu?'
  WHEN 131 THEN 'Where and when were nearly 1,000 massive stone statues carved and erected by an ancient civilization?'
  WHEN 132 THEN 'Where and when was an ancient city carved entirely from rose-red sandstone cliffs?'
  WHEN 133 THEN 'Where and when was a temple completed atop the Acropolis, dedicated to the goddess of wisdom?'
  WHEN 160 THEN 'Where and when was a massive concrete arch dam completed during the Great Depression?'
  WHEN 194 THEN 'Where and when was a Gothic cathedral completed with its famous flying buttresses and rose windows?'
  WHEN 195 THEN 'Where and when was the imperial palace complex completed that would house 24 emperors?'
  WHEN 196 THEN 'Where and when did an artist complete his masterpiece fresco on a chapel ceiling, depicting biblical scenes?'
  WHEN 197 THEN 'Where and when was a Sikh holy site completed, featuring a golden dome reflected in sacred waters?'
  WHEN 201 THEN 'Where and when did an undersea rail tunnel open, connecting two nations separated by a channel?'
  WHEN 203 THEN 'Where and when was a gleaming atomic model structure built for a world''s fair?'
  WHEN 204 THEN 'Where and when was a futuristic observation tower built for a world''s fair?'
  WHEN 205 THEN 'Where and when was a towering stainless steel arch completed, symbolizing a gateway to the west?'
  WHEN 206 THEN 'Where and when did a concrete communications tower become the world''s tallest free-standing structure?'
  WHEN 207 THEN 'Where and when was a basalt arch monument built to commemorate a royal visit?'
  WHEN 209 THEN 'Where and when was an Art Deco skyscraper completed that held the title of world''s tallest for 41 years?'
  WHEN 210 THEN 'Where and when did construction begin on an intricate basilica that remains unfinished to this day?'
  WHEN 213 THEN 'Where and when was a Greek Revival memorial completed honoring a president who preserved the union?'
  WHEN 215 THEN 'Where and when were gleaming twin towers completed that briefly held the record for world''s tallest?'
  WHEN 216 THEN 'Where and when was a tower with distinctive pink spheres completed as a TV and observation tower?'
  
  -- Wars & Battles  
  WHEN 97 THEN 'Where and when did jubilant crowds tear down a concrete barrier that had divided a city for 28 years?'
  WHEN 114 THEN 'Where and when did Allied forces storm heavily fortified beaches in the largest amphibious invasion in history?'
  WHEN 123 THEN 'Where and when was an archduke assassinated, triggering a chain of events that led to global war?'
  WHEN 125 THEN 'Where and when did a catastrophic fire destroy most of a major European city over four days?'
  WHEN 134 THEN 'Where and when did the Duke of Wellington''s forces decisively defeat Napoleon''s army?'
  WHEN 135 THEN 'Where and when was the first atomic bomb used in warfare, instantly vaporizing a city?'
  WHEN 139 THEN 'Where and when did Norman forces defeat the last Anglo-Saxon king, changing England forever?'
  WHEN 140 THEN 'Where and when did Ottoman forces finally breach the walls of the last Roman imperial city?'
  WHEN 144 THEN 'Where and when did Union and Confederate forces clash in the Civil War''s bloodiest three-day battle?'
  WHEN 155 THEN 'Where and when did Admiral Nelson achieve his greatest naval victory, though dying in the process?'
  WHEN 168 THEN 'Where and when did Athenian forces defeat a much larger Persian invasion force?'
  WHEN 172 THEN 'Where and when did 300 Spartans make their legendary last stand against a massive Persian army?'
  WHEN 180 THEN 'Where and when did Hannibal''s tactical genius result in one of history''s most devastating battlefield defeats?'
  WHEN 182 THEN 'Where and when did Alexander the Great''s phalanx decisively defeat the Persian Empire?'
  WHEN 191 THEN 'Where and when did Rome and a North African power begin their first of three brutal wars?'
  WHEN 245 THEN 'Where and when did American and French forces trap a British army, effectively ending the Revolutionary War?'
  WHEN 246 THEN 'Where and when did an American victory convince France to enter the Revolutionary War?'
  WHEN 247 THEN 'Where and when did "the shot heard round the world" mark the start of the American Revolution?'
  WHEN 248 THEN 'Where and when did the Civil War''s single bloodiest day occur, with over 22,000 casualties?'
  WHEN 249 THEN 'Where and when did Union forces capture a key Confederate stronghold controlling the Mississippi River?'
  WHEN 250 THEN 'Where and when did French and German forces fight one of WWI''s longest and costliest battles?'
  WHEN 251 THEN 'Where and when did British forces suffer 57,000 casualties on the first day of a devastating WWI offensive?'
  WHEN 252 THEN 'Where and when did Soviet forces turn the tide of WWII in a brutal urban battle?'
  WHEN 253 THEN 'Where and when did U.S. naval forces achieve a decisive victory that turned the tide in the Pacific?'
  WHEN 254 THEN 'Where and when did U.S. Marines capture a volcanic island in one of WWII''s bloodiest battles?'
  WHEN 255 THEN 'Where and when did Allied forces fight the last major battle of WWII in the Pacific?'
  WHEN 256 THEN 'Where and when did hundreds of civilian boats evacuate surrounded Allied troops from French beaches?'
  WHEN 257 THEN 'Where and when did Allied forces halt the Axis advance in North Africa?'
  WHEN 258 THEN 'Where and when did the largest tank battle in history take place on the Eastern Front?'
  WHEN 259 THEN 'Where and when did a daring amphibious assault reverse North Korean advances?'
  WHEN 260 THEN 'Where and when did a decisive battle end French colonial rule in Southeast Asia?'
  WHEN 261 THEN 'Where and when did a massive coordinated offensive begin that changed public opinion about a controversial war?'
  WHEN 264 THEN 'Where and when did U.S. troops massacre hundreds of Lakota Sioux, ending the Indian Wars?'
  WHEN 265 THEN 'Where and when did Lakota and Cheyenne warriors annihilate a U.S. cavalry regiment?'
  WHEN 292 THEN 'Where and when did Saladin''s forces decisively defeat Crusader armies?'
  WHEN 293 THEN 'Where and when did English longbowmen devastate French knights in an early Hundred Years'' War battle?'
  
  -- Disasters
  WHEN 103 THEN 'Where and when did an "unsinkable" luxury liner strike an iceberg on its maiden voyage?'
  WHEN 109 THEN 'Where and when did a nuclear reactor explode, creating the world''s worst nuclear disaster?'
  WHEN 149 THEN 'Where and when was a British ocean liner torpedoed, pushing the U.S. closer to war?'
  WHEN 151 THEN 'Where and when did a volcanic eruption bury two Roman cities under ash and pumice?'
  WHEN 154 THEN 'Where and when did a volcanic explosion create the loudest sound in recorded history?'
  WHEN 163 THEN 'Where and when did a massive earthquake and subsequent fires destroy most of a major West Coast city?'
  WHEN 184 THEN 'Where and when did a Bronze Age volcanic eruption possibly inspire the Atlantis myth?'
  
  -- Civil Rights & Social Movements
  WHEN 105 THEN 'Where and when was a beloved president assassinated while riding in an open motorcade?'
  WHEN 110 THEN 'Where and when was a civil rights leader assassinated on a motel balcony?'
  WHEN 113 THEN 'Where and when did a political prisoner walk free after 27 years of imprisonment?'
  WHEN 267 THEN 'Where and when did civil rights marchers face violent opposition on a bridge?'
  WHEN 268 THEN 'Where and when did a seamstress''s refusal to give up her bus seat spark a 381-day boycott?'
  WHEN 269 THEN 'Where and when did four college students begin sit-in protests at a segregated lunch counter?'
  WHEN 270 THEN 'Where and when did children face fire hoses and police dogs during civil rights protests?'
  WHEN 271 THEN 'Where and when did nine students require military escort to integrate a high school?'
  WHEN 272 THEN 'Where and when did pioneering women gather to demand equal rights and suffrage?'
  WHEN 266 THEN 'Where and when did Native American activists occupy a historic site for 71 days?'
  
  -- Ancient Civilizations
  WHEN 174 THEN 'Where and when did a king establish one of the first written legal codes?'
  WHEN 175 THEN 'Where and when was an ancient center of learning founded that housed countless scrolls?'
  WHEN 176 THEN 'Where and when were terraced gardens allegedly built for a homesick queen?'
  WHEN 177 THEN 'Where and when was a multilingual stone discovered that unlocked ancient hieroglyphics?'
  WHEN 178 THEN 'Where and when did athletes first gather for organized games honoring the gods?'
  WHEN 179 THEN 'Where and when did twins raised by a she-wolf legendarily establish a great empire''s capital?'
  WHEN 181 THEN 'Where and when was one of humanity''s oldest known epic poems recorded?'
  WHEN 185 THEN 'Where and when was the first known peace treaty in history signed between two great powers?'
  WHEN 186 THEN 'Where and when did a Bronze Age civilization flourish, leaving behind golden death masks?'
  WHEN 187 THEN 'Where and when did Mesoamerica''s first major civilization carve colossal stone heads?'
  WHEN 188 THEN 'Where and when did one of the world''s first urban civilizations thrive with advanced city planning?'
  WHEN 189 THEN 'Where and when did a powerful African kingdom control crucial trade routes?'
  WHEN 190 THEN 'Where and when was an elaborate palace complex built for a legendary king and a labyrinth?'
  WHEN 192 THEN 'Where and when did a remorseful emperor erect pillars inscribing his moral teachings?'
  WHEN 193 THEN 'Where and when did a catastrophic societal collapse end the Bronze Age?'
  
  -- American History
  WHEN 108 THEN 'Where and when did explorers rediscover an ancient Incan citadel hidden in misty peaks?'
  WHEN 112 THEN 'Where and when did a famous theme park open, pioneering modern entertainment?'
  WHEN 115 THEN 'Where and when did brothers open a restaurant that would become a global fast-food empire?'
  WHEN 117 THEN 'Where and when did half a million gather for three days of peace, love, and music?'
  WHEN 136 THEN 'Where and when did colonists disguised as natives dump valuable cargo into a harbor?'
  WHEN 138 THEN 'Where and when did colonial representatives sign a document declaring independence from Britain?'
  WHEN 146 THEN 'Where and when did an expedition begin that would map the western territories to the Pacific?'
  WHEN 147 THEN 'Where and when was a charter sealed that limited royal power and established rights?'
  WHEN 148 THEN 'Where and when were eastern and western rail lines joined with a golden spike?'
  WHEN 202 THEN 'Where and when did a mobster''s luxury hotel and casino help transform a desert town?'
  WHEN 208 THEN 'Where and when did a major exposition celebrate the completion of a crucial canal?'
  WHEN 211 THEN 'Where and when was a modernist capital city inaugurated, designed from scratch?'
  WHEN 212 THEN 'Where and when was a planned capital city officially named and established?'
  WHEN 220 THEN 'Where and when was a Spanish-style urban park created for a major exposition?'
  
  -- Scientific Discoveries
  WHEN 104 THEN 'Where and when did two bicycle mechanics achieve the first powered, controlled flight?'
  WHEN 106 THEN 'Where and when did a scientist accidentally discover a life-saving antibiotic on a petri dish?'
  WHEN 153 THEN 'Where and when was the first intelligible sentence transmitted by telephone?'
  WHEN 156 THEN 'Where and when did an inventor perfect a practical incandescent electric light bulb?'
  WHEN 161 THEN 'Where and when did a physicist discover electromagnetic radiation that could see through flesh?'
  WHEN 164 THEN 'Where and when was the first successful human-to-human heart transplant performed?'
  WHEN 166 THEN 'Where and when did an archaeologist discover an ancient pharaoh''s nearly intact tomb?'
  WHEN 169 THEN 'Where and when did a chemist invent a powerful explosive used in construction and warfare?'
  WHEN 171 THEN 'Where and when was a practical atmospheric engine developed that powered the Industrial Revolution?'
  
  -- Religious & Cultural  
  WHEN 137 THEN 'Where and when did revolutionaries storm a medieval fortress-prison, sparking a revolution?'
  WHEN 141 THEN 'Where and when did an inventor develop movable type printing, revolutionizing information?'
  WHEN 142 THEN 'Where and when did Spanish conquistadors conquer the Aztec capital after a brutal siege?'
  WHEN 143 THEN 'Where and when did a Genoese explorer first make landfall in the Americas?'
  WHEN 145 THEN 'Where and when did a tribunal begin its controversial campaign to enforce religious orthodoxy?'
  WHEN 152 THEN 'Where and when did mass hysteria lead to executions for alleged witchcraft?'
  WHEN 165 THEN 'Where and when did a teenage peasant girl lead French forces to break an English siege?'
  WHEN 274 THEN 'Where and when did seven consecutive popes reside outside of Rome?'
  WHEN 275 THEN 'Where and when did a monk nail 95 theses to a church door, sparking the Reformation?'
  WHEN 284 THEN 'Where and when did church leaders first gather to establish the Nicene Creed?'
  WHEN 287 THEN 'Where and when did the Catholic Church hold a major council to address the Protestant Reformation?'
  WHEN 290 THEN 'Where and when did a pope call for military expeditions to the Holy Land?'
  WHEN 291 THEN 'Where and when did Crusaders sack the Christian capital of the Eastern Roman Empire?'
  
  -- Treaties & Diplomacy
  WHEN 157 THEN 'Where and when was a peace treaty signed ending WWI, imposing harsh terms on the defeated?'
  WHEN 158 THEN 'Where and when was a Roman dictator assassinated by senators on the Ides of March?'
  WHEN 234 THEN 'Where and when did European powers redraw the map after Napoleon''s defeat?'
  WHEN 235 THEN 'Where and when did Allied leaders decide post-WWII Europe''s fate?'
  WHEN 236 THEN 'Where and when did three Allied leaders meet to discuss the final phase of WWII?'
  WHEN 237 THEN 'Where and when did an international conference partition a Southeast Asian nation?'
  WHEN 238 THEN 'Where and when did Middle Eastern leaders negotiate a framework for peace?'
  WHEN 239 THEN 'Where and when did Cold War superpowers'' leaders meet amid nuclear tensions?'
  WHEN 240 THEN 'Where and when were historic peace accords signed between Israel and the PLO?'
  WHEN 241 THEN 'Where and when was a peace agreement signed ending a Balkan conflict?'
  WHEN 242 THEN 'Where and when was a treaty brokered ending a war between two Asian powers?'
  WHEN 243 THEN 'Where and when was a treaty signed ending a war between Britain and the United States?'
  WHEN 244 THEN 'Where and when did a Confederate general surrender his army, effectively ending the Civil War?'
  WHEN 276 THEN 'Where and when did a treaty establish the principle that rulers could choose their territory''s religion?'
  WHEN 277 THEN 'Where and when did a series of treaties end the Thirty Years'' War?'
  WHEN 278 THEN 'Where and when was a treaty signed ending the First Opium War?'
  WHEN 279 THEN 'Where and when did an American commodore negotiate Japan''s opening to Western trade?'
  WHEN 281 THEN 'Where and when did Spain and Portugal divide the New World with a papal-sanctioned line?'
  WHEN 282 THEN 'Where and when did Russia sign a treaty with Germany to exit WWI?'
  WHEN 283 THEN 'Where and when was the charter signed establishing an organization for international cooperation?'
  
  -- Olympics & Sporting Events
  WHEN 121 THEN 'Where and when did rock legends perform at a historic dual-venue charity concert broadcast worldwide?'
  WHEN 221 THEN 'Where and when did a world''s fair celebrate the 400th anniversary of Columbus''s voyage?'
  WHEN 222 THEN 'Where and when were Summer Olympic Games held in the Southern Hemisphere for the first time?'
  WHEN 223 THEN 'Where and when did Summer Olympics feature memorable gymnastic perfection?'
  WHEN 224 THEN 'Where and when did an Asian nation host the Summer Olympics for the first time?'
  WHEN 225 THEN 'Where and when did Summer Olympics return to a West Coast city for the second time?'
  WHEN 226 THEN 'Where and when did Summer Olympics return to Britain''s capital for the third time?'
  WHEN 227 THEN 'Where and when did the Olympics return to their ancient birthplace?'
  WHEN 228 THEN 'Where and when did Cold War Olympics see political tensions alongside athletic competition?'
  WHEN 229 THEN 'Where and when were Olympics marred by a terrorist attack on Israeli athletes?'
  WHEN 230 THEN 'Where and when did Summer Olympics take place at high altitude, producing controversial records?'
  WHEN 231 THEN 'Where and when did post-Franco Olympics help transform a Mediterranean city?'
  WHEN 232 THEN 'Where and when were Olympics disrupted by a terrorist bombing in a public park?'
  WHEN 233 THEN 'Where and when did spectacular opening ceremonies mark Olympics in an Asian megacity?'
  
  -- Infrastructure & Engineering
  WHEN 119 THEN 'Where and when did a visionary inventor build a massive tower for wireless power transmission?'
  WHEN 126 THEN 'Where and when did the first drive-through window open at a fast-food restaurant?'
  WHEN 150 THEN 'Where and when did two brothers open a bicycle sales and repair shop?'
  WHEN 159 THEN 'Where and when was the world''s first regular high-definition television service launched?'
  WHEN 162 THEN 'Where and when did a pilot take off on the first solo transatlantic flight?'
  WHEN 167 THEN 'Where and when did the first aircraft hijacking in U.S. history occur?'
  WHEN 173 THEN 'Where and when did a massive canal open, connecting two oceans?'
  WHEN 198 THEN 'Where and when was a legendary railway connecting Europe and Asia completed?'
  WHEN 199 THEN 'Where and when was a crucial canal completed, shortening the Europe-to-India route?'
  WHEN 217 THEN 'Where and when was a colonial-era luxury hotel established that became legendary?'
  WHEN 218 THEN 'Where and when was a British colony returned to Chinese sovereignty?'
  WHEN 219 THEN 'Where and when did construction begin on a barrier dividing a city for 28 years?'
  
  -- Political Events
  WHEN 262 THEN 'Where and when did a CIA-backed invasion attempt to overthrow a Caribbean government?'
  WHEN 263 THEN 'Where and when did a crisis erupt over control of a crucial waterway?'
  WHEN 273 THEN 'Where and when did a suffragette throw herself under the King''s horse at a famous race?'
  WHEN 280 THEN 'Where and when did a treaty end the War of Spanish Succession?'
  WHEN 285 THEN 'Where and when did church leaders convene to address theological controversies?'
  WHEN 286 THEN 'Where and when did a council define key doctrines about Christ''s nature?'
  WHEN 288 THEN 'Where and when did a council declare papal infallibility?'
  WHEN 289 THEN 'Where and when did a council address the controversy over religious images?'
  
  -- Miscellaneous
  WHEN 183 THEN 'Where and when was a temple to a goddess completed atop a sacred hill?'
  WHEN 214 THEN 'Where and when was an opulent palace hotel opened in a wealthy Gulf state?'
  
  ELSE pt.clue_1_text
END
FROM puzzles p
WHERE pt.puzzle_id = p.id 
  AND pt.language_code = 'en';
